### ISSUE TITLE
piper tts pauses after each line

### ISSUE THREAD

**Issue by joshknnd1982** [mush42/piper-nvda#7] opened 2023-06-05 11:51 UTC
I noticed the latest piper tts addon pauses at the end of each line. It does not read complete sentences, can this be fixed? thanks.

**Comment by tmthywynn8** [comment] 2023-06-07 19:12
I suggest closing this as it is a duplicate of #4.

**Closed** 2023-06-08 17:03 UTC

**Comment by mush42** [comment] 2023-06-08 17:04
Duplicate of #4
